[package]
name = "irc_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
strum_macros = "0.25.2"

[dev-dependencies]
tcp-test = "0.1"